{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOJlvh9+OUnldz09YHMRkUh",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Rmjr007/Week-1/blob/main/ev_adoption.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "gNFvASbuOJ6n",
        "outputId": "0e369d50-621d-424a-baf7-baa601275fa4"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Loading dataset...\n",
            "\n",
            "✅ Dataset Loaded Successfully!\n",
            "Shape: (90, 12)\n",
            "\n",
            "--- First 5 rows ---\n",
            "         country  year  total_vehicles_registered  ev_vehicles_registered  \\\n",
            "0  United States  2015                   19942603                   46048   \n",
            "1  United States  2016                   20341455                   48523   \n",
            "2  United States  2017                   20748284                   53879   \n",
            "3  United States  2018                   21163249                   63042   \n",
            "4  United States  2019                   21586514                   77728   \n",
            "\n",
            "   ev_percentage_share  charging_stations_count  avg_cost_ev  \\\n",
            "0                 0.23                     8524     36696.32   \n",
            "1                 0.24                     9376     36559.14   \n",
            "2                 0.26                    10314     42585.59   \n",
            "3                 0.30                    11345     50944.18   \n",
            "4                 0.36                    12479     41397.82   \n",
            "\n",
            "   avg_cost_gasoline_vehicle  gov_incentive_amount  co2_emissions_per_vehicle  \\\n",
            "0                   31047.07                  9935                     108.69   \n",
            "1                   27580.33                  1434                     156.12   \n",
            "2                   26738.14                  5557                     180.94   \n",
            "3                   25103.76                  3547                     121.53   \n",
            "4                   25384.69                  6635                     160.37   \n",
            "\n",
            "   fuel_price_per_liter  electricity_price_per_kWh  \n",
            "0                  1.31                       0.11  \n",
            "1                  1.66                       0.24  \n",
            "2                  0.81                       0.26  \n",
            "3                  1.72                       0.12  \n",
            "4                  1.77                       0.25  \n",
            "\n",
            "--- Dataset Info ---\n",
            "<class 'pandas.core.frame.DataFrame'>\n",
            "RangeIndex: 90 entries, 0 to 89\n",
            "Data columns (total 12 columns):\n",
            " #   Column                     Non-Null Count  Dtype  \n",
            "---  ------                     --------------  -----  \n",
            " 0   country                    90 non-null     object \n",
            " 1   year                       90 non-null     int64  \n",
            " 2   total_vehicles_registered  90 non-null     int64  \n",
            " 3   ev_vehicles_registered     90 non-null     int64  \n",
            " 4   ev_percentage_share        90 non-null     float64\n",
            " 5   charging_stations_count    90 non-null     int64  \n",
            " 6   avg_cost_ev                90 non-null     float64\n",
            " 7   avg_cost_gasoline_vehicle  90 non-null     float64\n",
            " 8   gov_incentive_amount       90 non-null     int64  \n",
            " 9   co2_emissions_per_vehicle  90 non-null     float64\n",
            " 10  fuel_price_per_liter       90 non-null     float64\n",
            " 11  electricity_price_per_kWh  90 non-null     float64\n",
            "dtypes: float64(6), int64(5), object(1)\n",
            "memory usage: 8.6+ KB\n",
            "None\n",
            "\n",
            "--- Missing Values ---\n",
            "country                      0\n",
            "year                         0\n",
            "total_vehicles_registered    0\n",
            "ev_vehicles_registered       0\n",
            "ev_percentage_share          0\n",
            "charging_stations_count      0\n",
            "avg_cost_ev                  0\n",
            "avg_cost_gasoline_vehicle    0\n",
            "gov_incentive_amount         0\n",
            "co2_emissions_per_vehicle    0\n",
            "fuel_price_per_liter         0\n",
            "electricity_price_per_kWh    0\n",
            "dtype: int64\n",
            "\n",
            "✅ Missing values handled.\n",
            "✅ Removed 0 duplicate rows.\n",
            "\n",
            "✅ Columns renamed for consistency.\n",
            "Updated Columns: ['country', 'year', 'total_vehicles_registered', 'ev_vehicles_registered', 'ev_percentage_share', 'charging_stations_count', 'avg_cost_ev', 'avg_cost_gasoline_vehicle', 'gov_incentive_amount', 'co2_emissions_per_vehicle', 'fuel_price_per_liter', 'electricity_price_per_kwh']\n",
            "\n",
            "--- Descriptive Statistics ---\n",
            "              year  total_vehicles_registered  ev_vehicles_registered  \\\n",
            "count    90.000000               9.000000e+01            9.000000e+01   \n",
            "mean   2019.000000               4.466141e+07            2.091273e+08   \n",
            "std       2.596454               2.544288e+07            1.671432e+09   \n",
            "min    2015.000000               5.054484e+06            3.243100e+04   \n",
            "25%    2017.000000               2.169445e+07            7.685350e+04   \n",
            "50%    2019.000000               4.103634e+07            1.557385e+05   \n",
            "75%    2021.000000               7.045195e+07            5.498585e+05   \n",
            "max    2023.000000               8.938184e+07            1.577077e+10   \n",
            "\n",
            "       ev_percentage_share  charging_stations_count   avg_cost_ev  \\\n",
            "count            90.000000                90.000000     90.000000   \n",
            "mean            276.635556             14453.988889  44807.769000   \n",
            "std            2011.411451              9634.425254   8465.128515   \n",
            "min               0.060000              2164.000000  30166.340000   \n",
            "25%               0.232500              6488.750000  37885.402500   \n",
            "50%               0.555000             12618.500000  44506.155000   \n",
            "75%               1.672500             19704.750000  52162.325000   \n",
            "max           18646.150000             41544.000000  59421.660000   \n",
            "\n",
            "       avg_cost_gasoline_vehicle  gov_incentive_amount  \\\n",
            "count                  90.000000             90.000000   \n",
            "mean                27895.211667           5660.777778   \n",
            "std                  4367.745266           2518.836965   \n",
            "min                 20032.330000           1053.000000   \n",
            "25%                 24288.922500           3723.750000   \n",
            "50%                 27699.915000           5241.000000   \n",
            "75%                 31746.817500           7603.750000   \n",
            "max                 34976.820000           9976.000000   \n",
            "\n",
            "       co2_emissions_per_vehicle  fuel_price_per_liter  \\\n",
            "count                  90.000000             90.000000   \n",
            "mean                  148.555667              1.383889   \n",
            "std                    29.088352              0.359515   \n",
            "min                   100.720000              0.810000   \n",
            "25%                   124.127500              1.080000   \n",
            "50%                   149.130000              1.310000   \n",
            "75%                   171.642500              1.720000   \n",
            "max                   197.800000              2.000000   \n",
            "\n",
            "       electricity_price_per_kwh  \n",
            "count                  90.000000  \n",
            "mean                    0.196667  \n",
            "std                     0.054875  \n",
            "min                     0.100000  \n",
            "25%                     0.150000  \n",
            "50%                     0.190000  \n",
            "75%                     0.240000  \n",
            "max                     0.290000  \n",
            "⚠️ Columns for plotting not found.\n",
            "\n",
            "✅ Cleaned dataset saved as: ev_adoption_cleaned.csv\n",
            "\n",
            "🎉 Data cleaning complete! Ready for Week 2 (EDA & Model Building).\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/tmp/ipython-input-1981550644.py:36: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
            "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
            "\n",
            "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
            "\n",
            "\n",
            "  df[col].fillna(df[col].mode()[0], inplace=True)\n",
            "/tmp/ipython-input-1981550644.py:34: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.\n",
            "The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.\n",
            "\n",
            "For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.\n",
            "\n",
            "\n",
            "  df[col].fillna(df[col].mean(), inplace=True)\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 1000x600 with 0 Axes>"
            ]
          },
          "metadata": {}
        }
      ],
      "source": [
        "# week1_data_cleaning.py\n",
        "\n",
        "# -----------------------------\n",
        "# 🧩 Green Policy Simulator - Week 1\n",
        "# Dataset Cleaning & Exploration Script\n",
        "# -----------------------------\n",
        "\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "\n",
        "# 1️⃣ Load Dataset\n",
        "print(\"Loading dataset...\")\n",
        "df = pd.read_csv(\"ev_adoption_dataset.csv\")\n",
        "\n",
        "print(\"\\n✅ Dataset Loaded Successfully!\")\n",
        "print(f\"Shape: {df.shape}\")\n",
        "print(\"\\n--- First 5 rows ---\")\n",
        "print(df.head())\n",
        "\n",
        "# 2️⃣ Basic Info\n",
        "print(\"\\n--- Dataset Info ---\")\n",
        "print(df.info())\n",
        "\n",
        "# 3️⃣ Check for Missing Values\n",
        "print(\"\\n--- Missing Values ---\")\n",
        "print(df.isnull().sum())\n",
        "\n",
        "# 4️⃣ Handle Missing Data\n",
        "# Example: Fill numeric NaNs with mean, categorical with mode\n",
        "for col in df.columns:\n",
        "    if df[col].dtype in ['int64', 'float64']:\n",
        "        df[col].fillna(df[col].mean(), inplace=True)\n",
        "    else:\n",
        "        df[col].fillna(df[col].mode()[0], inplace=True)\n",
        "\n",
        "print(\"\\n✅ Missing values handled.\")\n",
        "\n",
        "# 5️⃣ Remove Duplicates\n",
        "before = df.shape[0]\n",
        "df.drop_duplicates(inplace=True)\n",
        "after = df.shape[0]\n",
        "print(f\"✅ Removed {before - after} duplicate rows.\")\n",
        "\n",
        "# 6️⃣ Fix Data Types (if applicable)\n",
        "if 'year' in df.columns:\n",
        "    df['year'] = df['year'].astype(int)\n",
        "if 'country' in df.columns:\n",
        "    df['country'] = df['country'].astype(str)\n",
        "\n",
        "# 7️⃣ Rename Columns (optional - improves readability)\n",
        "df.rename(columns=lambda x: x.strip().replace(\" \", \"_\").lower(), inplace=True)\n",
        "\n",
        "print(\"\\n✅ Columns renamed for consistency.\")\n",
        "print(\"Updated Columns:\", list(df.columns))\n",
        "\n",
        "# 8️⃣ Quick Data Summary\n",
        "print(\"\\n--- Descriptive Statistics ---\")\n",
        "print(df.describe())\n",
        "\n",
        "# 9️⃣ Visualization (optional for EDA)\n",
        "try:\n",
        "    plt.figure(figsize=(10, 6))\n",
        "    if 'year' in df.columns and 'ev_sales' in df.columns:\n",
        "        sns.lineplot(x='year', y='ev_sales', data=df)\n",
        "        plt.title(\"EV Sales Over the Years\")\n",
        "        plt.xlabel(\"Year\")\n",
        "        plt.ylabel(\"EV Sales\")\n",
        "        plt.grid(True)\n",
        "        plt.tight_layout()\n",
        "        plt.savefig(\"ev_sales_trend.png\")\n",
        "        print(\"\\n📊 Saved plot: ev_sales_trend.png\")\n",
        "    else:\n",
        "        print(\"⚠️ Columns for plotting not found.\")\n",
        "except Exception as e:\n",
        "    print(\"Plotting skipped due to:\", e)\n",
        "\n",
        "# 🔟 Save Cleaned Dataset\n",
        "df.to_csv(\"ev_adoption_cleaned.csv\", index=False)\n",
        "print(\"\\n✅ Cleaned dataset saved as: ev_adoption_cleaned.csv\")\n",
        "\n",
        "print(\"\\n🎉 Data cleaning complete! Ready for Week 2 (EDA & Model Building).\")"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "\n",
        "# Corrected file paths\n",
        "raw = pd.read_csv(\"/content/ev_adoption_dataset_raw.csv\")\n",
        "cleaned = pd.read_csv(\"/content/ev_adoption_dataset_clean.csv\")\n",
        "\n",
        "if raw.equals(cleaned):\n",
        "    print(\"✅ Raw and cleaned datasets are identical — data is already clean.\")\n",
        "else:\n",
        "    print(\"⚠️ Some changes occurred — cleaning modified the dataset.\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "1RqVMnwiUy7p",
        "outputId": "53840015-9f2f-475e-b853-b1458c7d5e8d"
      },
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "⚠️ Some changes occurred — cleaning modified the dataset.\n"
          ]
        }
      ]
    }
  ]
}