# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IH7pmcMTymQ6ApxNxUdmiaQMepNRIqW
"""

# week1_data_cleaning.py

# -----------------------------
# 🧩 Green Policy Simulator - Week 1
# Dataset Cleaning & Exploration Script
# -----------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1️⃣ Load Dataset
print("Loading dataset...")
df = pd.read_csv("ev_adoption_dataset.csv")

print("\n✅ Dataset Loaded Successfully!")
print(f"Shape: {df.shape}")
print("\n--- First 5 rows ---")
print(df.head())

# 2️⃣ Basic Info
print("\n--- Dataset Info ---")
print(df.info())

# 3️⃣ Check for Missing Values
print("\n--- Missing Values ---")
print(df.isnull().sum())

# 4️⃣ Handle Missing Data
# Example: Fill numeric NaNs with mean, categorical with mode
for col in df.columns:
    if df[col].dtype in ['int64', 'float64']:
        df[col].fillna(df[col].mean(), inplace=True)
    else:
        df[col].fillna(df[col].mode()[0], inplace=True)

print("\n✅ Missing values handled.")

# 5️⃣ Remove Duplicates
before = df.shape[0]
df.drop_duplicates(inplace=True)
after = df.shape[0]
print(f"✅ Removed {before - after} duplicate rows.")

# 6️⃣ Fix Data Types (if applicable)
if 'year' in df.columns:
    df['year'] = df['year'].astype(int)
if 'country' in df.columns:
    df['country'] = df['country'].astype(str)

# 7️⃣ Rename Columns (optional - improves readability)
df.rename(columns=lambda x: x.strip().replace(" ", "_").lower(), inplace=True)

print("\n✅ Columns renamed for consistency.")
print("Updated Columns:", list(df.columns))

# 8️⃣ Quick Data Summary
print("\n--- Descriptive Statistics ---")
print(df.describe())

# 9️⃣ Visualization (optional for EDA)
try:
    plt.figure(figsize=(10, 6))
    if 'year' in df.columns and 'ev_sales' in df.columns:
        sns.lineplot(x='year', y='ev_sales', data=df)
        plt.title("EV Sales Over the Years")
        plt.xlabel("Year")
        plt.ylabel("EV Sales")
        plt.grid(True)
        plt.tight_layout()
        plt.savefig("ev_sales_trend.png")
        print("\n📊 Saved plot: ev_sales_trend.png")
    else:
        print("⚠️ Columns for plotting not found.")
except Exception as e:
    print("Plotting skipped due to:", e)

# 🔟 Save Cleaned Dataset
df.to_csv("ev_adoption_cleaned.csv", index=False)
print("\n✅ Cleaned dataset saved as: ev_adoption_cleaned.csv")

print("\n🎉 Data cleaning complete! Ready for Week 2 (EDA & Model Building).")

import pandas as pd

# Corrected file paths
raw = pd.read_csv("/content/ev_adoption_dataset_raw.csv")
cleaned = pd.read_csv("/content/ev_adoption_dataset_clean.csv")

if raw.equals(cleaned):
    print("✅ Raw and cleaned datasets are identical — data is already clean.")
else:
    print("⚠️ Some changes occurred — cleaning modified the dataset.")